package by.tananushka.project.command;

public enum CommandName {
	AUTHENTICATION,
	CHANGE_LOCALE,
	VIEW_ADMIN_PROFILE,
	VIEW_PROFILE,
	NO_SUCH_COMMAND,
	REGISTRATION,
	REGISTRATION_INITIALIZE,
	LOGOUT,
	EMAIL_CONFIRMATION,
	SEND_MESSAGE,
	FILMS_AVAILABLE,
}
